# Generated by Django 2.2.6 on 2019-10-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
