# Generated by Django 2.2.6 on 2019-10-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
